<script lang="ts">
	import BrandMark from '$lib/components/BrandMark.svelte';
	import { Button } from '$lib/components/ui/button';
	import { PLANS } from '$lib/plans';
	import Seo from '$lib/components/Seo.svelte';
</script>

<Seo
	title="Terms of Service — anomalia/leads"
	description="The terms of using anomalia/leads: plans, limits, what we never do on your behalf, and how to leave."
/>

<header class="border-border/60 border-b">
	<div class="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
		<a href="/" class="flex items-center gap-2" aria-label="anomalia/leads">
			<BrandMark height={16} />
			<span class="font-medium tracking-tight">anomalia<span class="text-muted-foreground">/leads</span></span>
		</a>
		<Button href="/login" size="sm">Sign in</Button>
	</div>
</header>

<article class="mx-auto max-w-2xl px-6 py-16">
	<h1 class="font-semibold tracking-tight text-3xl">Terms of Service</h1>
	<p class="text-muted-foreground mt-2 text-sm">Last updated 2 September 2026.</p>

	<div class="mt-10 space-y-10 text-sm leading-relaxed">
		<section>
			<h2 class="text-foreground text-base font-medium">What you get</h2>
			<p class="text-muted-foreground mt-2 text-pretty">
				The service watches public conversations on the platforms you configure, ranks them by how
				close the writer appears to be to buying, and writes a draft reply for the ones worth
				answering. It hands you drafts. It does not publish them.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">What you are responsible for</h2>
			<p class="text-muted-foreground mt-2 text-pretty">
				You publish. Whatever you paste is your comment, from your account, under the rules of that
				platform — including its disclosure rules for commercial interest. Read the draft before you
				post it: it is generated by a language model and can be wrong about your product.
			</p>
			<p class="text-muted-foreground mt-3 text-pretty">
				Automating publication of these drafts is against the terms of every platform we read, and
				against these. Do not do it.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">Acceptable use</h2>
			<ul class="text-muted-foreground mt-2 space-y-1.5">
				<li>Do not use the service to contact somebody who has asked not to be contacted.</li>
				<li>Do not remove the opt-out line from a direct message draft.</li>
				<li>Do not use it to harass, impersonate, or mislead.</li>
				<li>Do not resell the drafts as a service without telling us.</li>
			</ul>
			<p class="text-muted-foreground mt-3 text-pretty">
				The do-not-contact list is shared across all customers and is not something you can switch
				off for your account. That is the point of it.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">Plans and payment</h2>
			<p class="text-muted-foreground mt-2 text-pretty">
				Plans are metered by drafts delivered in a month, not by keywords monitored:
			</p>
			<ul class="text-muted-foreground mt-2 space-y-1.5">
				{#each PLANS as p (p.id)}
					<li>
						<strong class="text-foreground font-medium">{p.name}</strong> —
						{#if p.eur === 0}free{:else}€{p.eur} / ${p.usd} per month{/if},
						{p.draftsPerMonth.toLocaleString('en-US')} drafts,
						{p.sources === null ? 'unlimited sources' : `${p.sources} sources`}.
					</li>
				{/each}
			</ul>
			<p class="text-muted-foreground mt-3 text-pretty">
				A paid plan renews monthly until cancelled, and cancelling stops the next renewal — it does
				not refund the current month. Unused drafts do not carry over.
			</p>
			<p class="text-muted-foreground mt-3 text-pretty">
				<strong class="text-foreground font-medium">Thirty days.</strong> If your first month passes
				without a single conversation worth answering, write to us and you will not be charged.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">What we do not promise</h2>
			<p class="text-muted-foreground mt-2 text-pretty">
				We do not promise a number of leads, a reply rate, or a sale. Some months are quiet, and the
				product is built to stay quiet rather than manufacture drafts to fill a quota. We depend on
				platforms we do not control: one of them changing its access can reduce or stop what the
				service can read.
			</p>
			<p class="text-muted-foreground mt-3 text-pretty">
				The service is provided as is, without warranty. To the extent the law allows, our liability
				is limited to what you paid in the previous twelve months.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">Ending it</h2>
			<p class="text-muted-foreground mt-2 text-pretty">
				You can delete your account at any time. We can suspend an account that breaks the
				acceptable-use rules above, and will say why.
			</p>
		</section>

		<section>
			<h2 class="text-foreground text-base font-medium">Contact</h2>
			<p class="text-muted-foreground mt-2">
				<a href="mailto:legal@anomalia.so" class="hover:text-foreground underline underline-offset-4">legal@anomalia.so</a>
			</p>
		</section>
	</div>

	<div class="border-border mt-14 border-t pt-6">
		<a href="/" class="text-muted-foreground hover:text-foreground text-sm underline underline-offset-4">
			Back to the homepage
		</a>
	</div>
</article>
